sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

stages:
  - name: deploy docker image
    if: branch = master

jobs:
  include:
    - stage: deploy docker image
      script: scripts/deploy_image.sh

addons:
  apt:
    packages:
      - docker-ce

