sudo: required

language: node_js

node_js:
  - "10.15.3"

branches:
  - master

services:
  - docker

before_script:
  - docker build -t frontend .

script:
  - docker run frontend npm run build

deploy:
  - provider: script
    script: bash scripts/deploy_image.sh
    on:
      branch: master
  
addons:
  apt:
    packages:
      - docker-ce
